# Generated by Django 3.1.6 on 2021-03-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, editable=False)),
                ('acltext', models.JSONField()),
                ('is_executed', models.BooleanField(default=False, null=True)),
                ('owner', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
