# Generated by Django 3.1.6 on 2021-03-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='id',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
