# Generated by Django 3.1.6 on 2021-03-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0002_auto_20210301_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='acltext',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='acl',
            name='owner',
            field=models.CharField(blank=True, default='admin', max_length=64),
        ),
    ]
