# Generated by Django 3.1.6 on 2021-03-02 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0003_auto_20210301_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='acl',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
