# Generated by Django 3.1.6 on 2021-03-02 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0004_acl_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 2)),
        ),
    ]
