# Generated by Django 3.1.6 on 2021-03-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0005_auto_20210302_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
