# Generated by Django 3.1.6 on 2021-03-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0006_auto_20210302_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
