# Generated by Django 3.1.6 on 2021-03-09 11:11

from django.db import migrations, models
import django.db.models.deletion
import ownerlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0014_owners_department'),
        ('accesslist', '0009_acl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='owner',
            field=models.ForeignKey(default=ownerlist.models.Owners.get_default_owner, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ownerlist.owners'),
        ),
    ]
