# Generated by Django 3.1.6 on 2021-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0012_acl_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='taskid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
