# Generated by Django 3.1.6 on 2021-06-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0014_auto_20210603_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='status',
            field=models.CharField(blank=True, choices=[('NOTFL', 'Не заполнено'), ('FL', 'Заполнено'), ('CMP', 'Выполнено'), ('WTE', 'Ожидает рассмотрения'), ('APRV', 'Согласованно'), ('CNL', 'Отклонено')], default='NOTFL', max_length=20),
        ),
    ]
