# Generated by Django 3.1.6 on 2021-06-22 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accesslist', '0015_auto_20210622_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='acl',
            name='approve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_persone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acl',
            name='status',
            field=models.CharField(blank=True, choices=[('NOTFL', 'Не заполнено'), ('FL', 'Заполнено'), ('CMP', 'Выполнено'), ('WTE', 'Ожидает согласования'), ('APRV', 'Согласованно'), ('CNL', 'Отклонено')], default='NOTFL', max_length=20),
        ),
    ]
