# Generated by Django 3.1.6 on 2021-06-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslist', '0017_acl_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='token',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
