# Generated by Django 3.1.6 on 2021-02-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(blank=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Имя владельца')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default', max_length=128, unique=True, verbose_name='Имя тега')),
            ],
        ),
        migrations.CreateModel(
            name='Vlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя VLAN')),
                ('location', models.CharField(blank=True, max_length=64)),
                ('subnet', models.CharField(blank=True, max_length=15)),
                ('vlan', models.IntegerField(default=0)),
                ('mask', models.IntegerField(default=24)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='ownerlist.Tags', verbose_name='tags')),
            ],
        ),
        migrations.CreateModel(
            name='Iplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP адресс')),
                ('ipv4_int', models.BigIntegerField(db_index=True, default=0)),
                ('hostname', models.CharField(blank=True, max_length=64)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerlist.owners')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='ownerlist.Tags', verbose_name='tags')),
                ('vlan', models.ManyToManyField(blank=True, null=True, to='ownerlist.Vlans', verbose_name='vlans')),
            ],
        ),
    ]
