# Generated by Django 3.1.6 on 2021-02-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpTags',
        ),
        migrations.AlterField(
            model_name='iplist',
            name='owner',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
