# Generated by Django 3.1.6 on 2021-02-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
