# Generated by Django 3.1.6 on 2021-02-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0002_auto_20210210_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='Unknown', max_length=128, verbose_name='Имя владельца')),
            ],
        ),
        migrations.AlterField(
            model_name='iplist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerlist.owners'),
        ),
    ]
