# Generated by Django 3.1.6 on 2021-02-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0003_auto_20210210_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='owner',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='ownerlist.owners'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='username',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя владельца'),
        ),
    ]
