# Generated by Django 3.1.6 on 2021-02-10 17:09

from django.db import migrations, models
import django.db.models.deletion
import ownerlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0005_auto_20210210_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='owner',
            field=models.ForeignKey(default=ownerlist.models.Owners.get_default_owner, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ownerlist.owners'),
        ),
    ]
