# Generated by Django 3.1.6 on 2021-02-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0006_auto_20210210_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
