# Generated by Django 3.1.6 on 2021-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0008_auto_20210210_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='username',
            field=models.CharField(blank=True, max_length=256, verbose_name='Имя владельца'),
        ),
    ]
