# Generated by Django 3.1.6 on 2021-02-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0010_iplist_ipv4_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False, verbose_name='Is result')),
                ('username', models.CharField(blank=True, max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ipv4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ownerlist.iplist')),
            ],
        ),
    ]
