# Generated by Django 3.1.6 on 2021-02-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0011_historycall'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='owners',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='owners',
            name='phone',
            field=models.CharField(blank=True, max_length=256, verbose_name='Телефон'),
        ),
    ]
