# Generated by Django 3.1.6 on 2021-03-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0012_auto_20210228_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='ipv4',
            field=models.GenericIPAddressField(db_index=True, protocol='IPv4', unique=True, verbose_name='IP адресс'),
        ),
    ]
