# Generated by Django 3.1.6 on 2021-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerlist', '0013_auto_20210308_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='department',
            field=models.CharField(blank=True, max_length=256, verbose_name='Департамент'),
        ),
    ]
